[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdfplumber>=0.11.6",
    "psutil>=7.0.0",
    "pymupdf>=1.26.0",
]
